# Production override for Docker Compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  inspection-service:
    build:
      context: ./inspection-service
      dockerfile: Dockerfile
      target: production  # Use production stage
    environment:
      - NODE_ENV=production
    volumes: []  # Remove volume mounts for production
    restart: always  # Always restart in production 