# Docker Compose for PDF Scanner Extension - Local Development
# 
# Usage:
#   Development mode with hot-reload: docker-compose up
#   Production mode: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
#   Rebuild after code changes: docker-compose up --build
#   Run in background: docker-compose up -d
#   Stop services: docker-compose down
#   View logs: docker-compose logs -f inspection-service

version: '3.8'

services:
  # PDF Inspection Service
  inspection-service:
    build:
      context: ./inspection-service
      dockerfile: Dockerfile
      target: development  # Use development stage for hot-reload
    container_name: pdf-scanner-inspection
    ports:
      - "3001:3001"  # Map container port 3001 to host port 3001
    environment:
      - NODE_ENV=development
      - INSPECTION_PORT=3001
      - PORT=3001
      # Prompt Security API configuration (optional - set these in .env)
      - PROMPT_SECURITY_APP_ID=${PROMPT_SECURITY_APP_ID:-}
      - PROMPT_SECURITY_API_KEY=${PROMPT_SECURITY_API_KEY:-}
    volumes:
      # Mount source code for hot-reload during development
      - ./inspection-service:/app:cached
      - /app/node_modules  # Anonymous volume to preserve node_modules
    env_file:
      - ./inspection-service/.env  # Load environment variables from .env file
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - pdf-scanner-network

  # You can add other services here (e.g., database, redis, monitoring)
  # when needed for future enhancements

networks:
  pdf-scanner-network:
    driver: bridge
    name: pdf-scanner-net

# Development environment notes:
# 1. Make sure you have a .env file in the inspection-service directory
# 2. The service will restart automatically when you change code files
# 3. Logs are available via: docker-compose logs -f inspection-service
# 4. To access the service: http://localhost:3001/health
# 5. For production deployment, use docker-compose.prod.yml override 